dayksx/ai-cns

- .gitignore
- client/src/components/app-sidebar.tsx
- client/src/components/connect-wallet-button.tsx
- client/src/components/page-header.tsx
- client/src/routes/naturalization.tsx
> added connect button

- client/src/contracts/Initiative.ts
- client/src/contracts/get-initiatives.ts
- client/src/contracts/get-user-credits.ts
- client/src/routes/governance.tsx
> updated Governance page logic with credit points and voting system

- .env.example
- client/src/cns-constitution.ts
- client/src/components/app-sidebar.tsx
- client/src/components/cns/cns-activities-column.tsx
- client/src/components/cns/cns-activities.tsx
- client/src/components/cns/cns-core-goods.tsx
- client/src/components/cns/cns-core-needs.tsx
- client/src/components/cns/cns-treasury.tsx
- client/src/contracts/Initiative.ts
- client/src/lib/viem-utils.ts
- client/src/routes/census.tsx
- client/src/routes/naturalization.tsx
- client/vite.config.ts
> Added activities in census and signing in naturalization flow

- client/src/contracts/get-user-credits.ts
- client/src/routes/governance.tsx
> refreshed goverenance page after voting is done

- client/src/routes/governance.tsx
> added launch idea logic in governance page

- smart-contract/contracts/CNSToken.sol
- smart-contract/contracts/NetworkStateAgreement.sol
- smart-contract/contracts/NetworkStateInitiatives.sol
- smart-contract/scripts/Agreement.json
- smart-contract/scripts/deploy-Agreement.ts
- smart-contract/scripts/deploy-Initiatives.ts
- smart-contract/scripts/deploy.ts
- smart-contract/test/unit/networkstateagreement/networkstateagreement.fixture.ts
- smart-contract/test/unit/networkstateinitiatives/networkstateinitiatives.ts
> Update Smart Contract

- client/src/components/app-sidebar.tsx
- client/src/routes/allocation.tsx
- pnpm-lock.yaml
> Feature UI updates

- client/src/components/account-info.tsx
- client/src/components/userprofile/connected-nodes.tsx
- client/src/contracts/get-user-activities.ts
- client/src/routes/governance.tsx
- client/src/routes/userprofile.tsx
> improved styles of governance and profile pages

- client/src/components/account-info.tsx
- client/src/routes/userprofile.tsx
> styled profile page

- client/src/components/cns/cns-demography.tsx
- client/src/components/userprofile/account-card-short.tsx
- client/src/components/userprofile/account-grid-short.tsx
- client/src/components/userprofile/jazzicon.tsx
> added grid view on census page for netizens

- client/src/components/account-info.tsx
- client/src/components/userprofile/connected-nodes.tsx
> aligned profile page

- client/src/App.tsx
- client/src/components/account-info.tsx
- client/src/components/app-sidebar.tsx
- client/src/components/userprofile/account-grid-short.tsx
- client/src/routes/all-netizens.tsx
- client/src/routes/userprofile.tsx
- client/src/verax/attestations-reader.ts
> added discover netizens page

- client/src/components/cns/initiative-capital-allocation.tsx
- client/src/routes/allocation.tsx
> changed styling on allocation page

- client/src/components/connect-wallet-button.tsx
- client/src/components/userprofile/account-card-short.tsx
- client/src/components/userprofile/account-grid-short.tsx
> few ui fixes for styles

- client/src/components/cns/cns-activities-column.tsx
- client/src/components/cns/cns-activities.tsx
- client/src/components/cns/cns-core-goods.tsx
- client/src/components/cns/cns-demography.tsx
- client/src/components/cns/cns-treasury.tsx
- client/src/components/cns/finance-chart.tsx
> Feature UI

- client/package.json
- client/src/abi/Initiative.abi.ts
- client/src/abi/NetworkAgreement.abi.ts
- client/src/components/cns/initiative-capital-allocation.tsx
- client/src/contracts/get-initiatives.ts
- client/src/contracts/get-team-members.ts
- client/src/contracts/get-user-activities.ts
- client/src/routes/allocation.tsx
- client/src/routes/userprofile.tsx
- pnpm-lock.yaml
> added fund allocation, joining leaving team features

- client/src/components/account-info.tsx
- client/src/components/cns/address.tsx
- client/src/components/userprofile/account-card-short.tsx
> added hardcoded ens names

- client/src/components/cns/initiative-capital-allocation.tsx
- client/src/routes/naturalization.tsx
- pnpm-lock.yaml
> added withdraw feature and extra checks on naturlisation

- client/src/routes/naturalization.tsx
> added extra checks on naturlisation

- client/src/routes/naturalization.tsx
> minor alignment and style fixes

- client/src/routes/naturalization.tsx
> style fixes

- client/src/routes/naturalization.tsx
> added some margin on naturalisation boxes and content

- client/src/components/account-info.tsx
- client/src/contracts/get-projects-for-user.ts
> added projects section on user profile

- client/src/components/account-info.tsx
> added styling to project tiles on profile page

- client/src/components/account-info.tsx
- client/src/contracts/get-projects-for-user.ts
- pnpm-lock.yaml
> fixed build errors

- smart-contract/contracts/NetworkStateAgreement.sol
- smart-contract/contracts/NetworkStateInitiatives.sol
- smart-contract/scripts/Agreement.json
- smart-contract/scripts/CNSToken.json
- smart-contract/scripts/Initiatives.json
- smart-contract/scripts/deploy-Agreement.ts
- smart-contract/scripts/deploy-CNSToken.ts
- smart-contract/scripts/deploy-Initiatives.ts
- smart-contract/test/common/types.ts
- smart-contract/test/unit/networkstateagreement/networkstateagreement.fixture.ts
- smart-contract/test/unit/networkstateagreement/networkstateagreement.ts
- smart-contract/test/unit/networkstatecnstoken/networkstatecnstoken.fixture.ts
- smart-contract/test/unit/networkstatecnstoken/networkstatecnstoken.ts
- smart-contract/test/unit/networkstateinitiatives/networkstateinitiatives.fixture.ts
- smart-contract/test/unit/networkstateinitiatives/networkstateinitiatives.ts
> Feature smartcontract

- .gitmodules
- agent/package.json
- characters/lubAIn.character.json
- packages/plugin-ideation/src/actions/registerIdea.ts
- pnpm-lock.yaml
> Feature twitter

- .gitmodules
- agent/package.json
- agent/src/index.ts
- characters/lubAIn.character.json
- characters/satoshAI.character.json
- characters/vitalAIk.character.json
- packages/plugin-ideation/src/providers/ideas.ts
- pnpm-lock.yaml
> add web search plugin
